| Project                                | Libraries                                        | Topics Covered                                                  |
| -------------------------------------- | ------------------------------------------------ | --------------------------------------------------------------- |
| **1. Text Preprocessing Pipeline**     | NLTK, spaCy, re, Pandas                          | Tokenization, Stopwords, Lemmatization, Regex, Text Cleaning    |

🔤 Text Cleaning & Normalization

Lowercasing

Removing punctuation

Removing numbers

Removing extra whitespace

Expanding contractions (e.g., don’t → do not)

Removing special characters or HTML tags

🧹 Token-Level Processing

Tokenization (splitting text into words, sentences, or subwords)

Lemmatization (reduce words to dictionary form, e.g., running → run)

Stemming (reduce words to root form, e.g., running → run)

Stopword removal (filter out common words like the, is, and)

Handling negations (e.g., not good → not_good)

In [131]:
# Importing libraries
import numpy as np
import pandas as pd
import nltk
import re
import contractions

**Text Cleaning and Normalization**

In [132]:
# Text and Dataframe
text = '''Hello!!! My name's Himanshu, and I'm learning NLP 😊.  
I have 2 cats, 3 dogs, and 1 parrot.  
Sometimes I write like THIS, sometimes like this...  
BTW, check out my blog at https://myblog.com or email me at test_user123@example.com.  
Don't forget to follow me @coolguy and use #MachineLearning #DataScience.  
Prices went up by 50% in 2025, but now they're stable.  
Ummm...   too   many   spaces   here.  
'''

data = {
    "Text1": ["Hello world!!!", "Natural Language 2025", "Data   Science", "Machine-Learning 😊"],
    "Text2": ["Regex basics...", "Tokenization @user", "Preprocessing #NLP studies", "Embeddings https://example.com"],
    "Number": [10, 20, 30, 40]
}

df = pd.DataFrame(data)
df

                   Text1                           Text2  Number
0         Hello world!!!                 Regex basics...      10
1  Natural Language 2025              Tokenization @user      20
2         Data   Science      Preprocessing #NLP studies      30
3     Machine-Learning 😊  Embeddings https://example.com      40

`isinstance(object, classinfo)`

object → the variable or value you want to check.

classinfo → the type(s) you want to test against.

In [133]:
# Lowercasing text
text = text.lower()
print(text)

# Lowercasing DataFrame
df = df.map(lambda s : s.lower() if isinstance(s, str) else s)
df

hello!!! my name's himanshu, and i'm learning nlp 😊.
i have 2 cats, 3 dogs, and 1 parrot.
sometimes i write like this, sometimes like this...
btw, check out my blog at https://myblog.com or email me at test_user123@example.com.
don't forget to follow me @coolguy and use #machinelearning #datascience.
prices went up by 50% in 2025, but now they're stable.
ummm...   too   many   spaces   here.

                   Text1                           Text2  Number
0         hello world!!!                 regex basics...      10
1  natural language 2025              tokenization @user      20
2         data   science      preprocessing #nlp studies      30
3     machine-learning 😊  embeddings https://example.com      40

In [134]:
# Handling Contractions in text
text = contractions.fix(text)
print(text)

# Handling contractions in DataFrame
def handle_contraction(text):
    return contractions.fix(text)
df['Text1'] = df['Text1'].apply(handle_contraction)
df['Text2'] = df['Text2'].apply(handle_contraction)
df

hello!!! my name's himanshu, and i am learning nlp 😊.
i have 2 cats, 3 dogs, and 1 parrot.
sometimes i write like this, sometimes like this...
by the way, check out my blog at https://myblog.com or email me at test_user123@example.com.
do not forget to follow me @coolguy and use #machinelearning #datascience.
prices went up by 50% in 2025, but now they are stable.
ummm...   too   many   spaces   here.

                   Text1                           Text2  Number
0         hello world!!!                 regex basics...      10
1  natural language 2025              tokenization @user      20
2         data   science      preprocessing #nlp studies      30
3     machine-learning 😊  embeddings https://example.com      40

`re.sub(pattern, repl, string, count=0, flags=0)`

In [135]:
# Removing Punctuations from text
text = re.sub(r"[^\w\s]", "", text)
print(text)

# Removing Punctuations from DataFrame
def remove_punctuation(text):
    return re.sub(r"[^\w\s]", "", text)
df['Text1'] = df['Text1'].apply(remove_punctuation)
df['Text2'] = df['Text2'].apply(remove_punctuation)
df

hello my names himanshu and i am learning nlp
i have 2 cats 3 dogs and 1 parrot
sometimes i write like this sometimes like this
by the way check out my blog at httpsmyblogcom or email me at test_user123examplecom
do not forget to follow me coolguy and use machinelearning datascience
prices went up by 50 in 2025 but now they are stable
ummm   too   many   spaces   here

                   Text1                       Text2  Number
0            hello world                regex basics      10
1  natural language 2025           tokenization user      20
2         data   science   preprocessing nlp studies      30
3       machinelearning   embeddings httpsexamplecom      40

In [136]:
# Removing numbers from text
text = re.sub(r"\d+", "", text)
print(text)

# Removing numbers from DataFrame
def remove_num(text):
    return re.sub(r"\d+", "", text)
df['Text1'] = df['Text1'].apply(remove_num)
df['Text2'] = df['Text2'].apply(remove_num)
df

hello my names himanshu and i am learning nlp
i have  cats  dogs and  parrot
sometimes i write like this sometimes like this
by the way check out my blog at httpsmyblogcom or email me at test_userexamplecom
do not forget to follow me coolguy and use machinelearning datascience
prices went up by  in  but now they are stable
ummm   too   many   spaces   here

               Text1                       Text2  Number
0        hello world                regex basics      10
1  natural language            tokenization user      20
2     data   science   preprocessing nlp studies      30
3   machinelearning   embeddings httpsexamplecom      40

In [137]:
# Remove white spaces from Text
text = re.sub(r"\s", " ", text)
print(text)

# Removing white spaces from DstaFrame
def remove_spaces(text):
    return re.sub(r"\s", " ", text)
df['Text1'] = df['Text1'].apply(remove_spaces)
df['Text2'] = df['Text2'].apply(remove_spaces)
df

hello my names himanshu and i am learning nlp    i have  cats  dogs and  parrot   sometimes i write like this sometimes like this   by the way check out my blog at httpsmyblogcom or email me at test_userexamplecom   do not forget to follow me coolguy and use machinelearning datascience   prices went up by  in  but now they are stable   ummm   too   many   spaces   here

               Text1                       Text2  Number
0        hello world                regex basics      10
1  natural language            tokenization user      20
2     data   science   preprocessing nlp studies      30
3   machinelearning   embeddings httpsexamplecom      40

**Token Level Processing**

In [138]:
from nltk.tokenize import word_tokenize
nltk.download('punkt')

# TOkenization of text
text = word_tokenize(text)
print(text)

# TOkenization of DataFrame
df['Text1'] = df['Text1'].apply(word_tokenize)
df['Text2'] = df['Text2'].apply(word_tokenize)
df

['hello', 'my', 'names', 'himanshu', 'and', 'i', 'am', 'learning', 'nlp', 'i', 'have', 'cats', 'dogs', 'and', 'parrot', 'sometimes', 'i', 'write', 'like', 'this', 'sometimes', 'like', 'this', 'by', 'the', 'way', 'check', 'out', 'my', 'blog', 'at', 'httpsmyblogcom', 'or', 'email', 'me', 'at', 'test_userexamplecom', 'do', 'not', 'forget', 'to', 'follow', 'me', 'coolguy', 'and', 'use', 'machinelearning', 'datascience', 'prices', 'went', 'up', 'by', 'in', 'but', 'now', 'they', 'are', 'stable', 'ummm', 'too', 'many', 'spaces', 'here']

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SAI\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

                 Text1                          Text2  Number
0       [hello, world]                [regex, basics]      10
1  [natural, language]           [tokenization, user]      20
2      [data, science]  [preprocessing, nlp, studies]      30
3    [machinelearning]  [embeddings, httpsexamplecom]      40

In [139]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

# Lemmatization of Text 
lemmatizer = WordNetLemmatizer()
text = [lemmatizer.lemmatize(w) for w in text]
print(text)

# lemmatization in DataFrame 
def lemmatization(text):
    return [lemmatizer.lemmatize(w) for w in text]
df['Text1'] = df['Text1'].apply(lemmatization)
df['Text2'] = df['Text2'].apply(lemmatization)
df

['hello', 'my', 'name', 'himanshu', 'and', 'i', 'am', 'learning', 'nlp', 'i', 'have', 'cat', 'dog', 'and', 'parrot', 'sometimes', 'i', 'write', 'like', 'this', 'sometimes', 'like', 'this', 'by', 'the', 'way', 'check', 'out', 'my', 'blog', 'at', 'httpsmyblogcom', 'or', 'email', 'me', 'at', 'test_userexamplecom', 'do', 'not', 'forget', 'to', 'follow', 'me', 'coolguy', 'and', 'use', 'machinelearning', 'datascience', 'price', 'went', 'up', 'by', 'in', 'but', 'now', 'they', 'are', 'stable', 'ummm', 'too', 'many', 'space', 'here']

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SAI\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

                 Text1                          Text2  Number
0       [hello, world]                 [regex, basic]      10
1  [natural, language]           [tokenization, user]      20
2      [data, science]    [preprocessing, nlp, study]      30
3    [machinelearning]  [embeddings, httpsexamplecom]      40

In [140]:
from nltk.stem import PorterStemmer

# Stemming of Text
stemmer = PorterStemmer()
text = [stemmer.stem(w) for w in text]
print(text)

# Stemming in DataFrame
def stemm(text):
    return [stemmer.stem(w) for w in text]
df['Text1'] = df['Text1'].apply(stemm)
df['Text2'] = df['Text2'].apply(stemm)
df

['hello', 'my', 'name', 'himanshu', 'and', 'i', 'am', 'learn', 'nlp', 'i', 'have', 'cat', 'dog', 'and', 'parrot', 'sometim', 'i', 'write', 'like', 'thi', 'sometim', 'like', 'thi', 'by', 'the', 'way', 'check', 'out', 'my', 'blog', 'at', 'httpsmyblogcom', 'or', 'email', 'me', 'at', 'test_userexamplecom', 'do', 'not', 'forget', 'to', 'follow', 'me', 'coolguy', 'and', 'use', 'machinelearn', 'datasci', 'price', 'went', 'up', 'by', 'in', 'but', 'now', 'they', 'are', 'stabl', 'ummm', 'too', 'mani', 'space', 'here']

              Text1                     Text2  Number
0    [hello, world]            [regex, basic]      10
1  [natur, languag]             [token, user]      20
2    [data, scienc]  [preprocess, nlp, studi]      30
3    [machinelearn]  [embed, httpsexamplecom]      40

In [141]:
from nltk.corpus import stopwords
nltk.download('stopwords')

stopword = stopwords.words('English')
text = [w for w in text if w not in stopword]
print(text)

def remove_stopwords(text):
    return [w for w in text if w not in stopword]
df['Text1'] = df['Text1'].apply(remove_stopwords)
df['Text2'] = df['Text2'].apply(remove_stopwords)
df

['hello', 'name', 'himanshu', 'learn', 'nlp', 'cat', 'dog', 'parrot', 'sometim', 'write', 'like', 'thi', 'sometim', 'like', 'thi', 'way', 'check', 'blog', 'httpsmyblogcom', 'email', 'test_userexamplecom', 'forget', 'follow', 'coolguy', 'use', 'machinelearn', 'datasci', 'price', 'went', 'stabl', 'ummm', 'mani', 'space']

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SAI\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

              Text1                     Text2  Number
0    [hello, world]            [regex, basic]      10
1  [natur, languag]             [token, user]      20
2    [data, scienc]  [preprocess, nlp, studi]      30
3    [machinelearn]  [embed, httpsexamplecom]      40